apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekstutorial
  labels:
    app: ekstutorial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ekstutorial
  template:
    metadata:
      labels:
        app: ekstutorial
    spec:
      containers:
        - name: ekstutorial
          image: 767397800207.dkr.ecr.us-east-1.amazonaws.com/eks_tutorial:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080