apiVersion: apps/v1
kind: Deployment
metadata:
  name: eksdemo
  labels:
    app: eksdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eksdemo
  template:
    metadata:
      labels:
        app: eksdemo
    spec:
      containers:
        - name: eksdemo
          image: 274127640471.dkr.ecr.us-east-2.amazonaws.com/eksdemo:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080