apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks_tutorial
  labels:
    app: eks_tutorial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks_tutorial
  template:
    metadata:
      labels:
        app: eks_tutorial
    spec:
      containers:
        - name: eks_tutorial
          image: 767397800207.dkr.ecr.us-east-1.amazonaws.com/eks_tutorial:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080